### ISSUE TITLE
Error in config? (Fixed)

### ISSUE THREAD

**Issue by nazarhktwitch** [Phyronnaz/PluginDownloader#14]
Could not find current commit: Command 'git log -n 1 --pretty=format:"%H"' returned non-zero exit status 128.
D:\Python\Lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.20) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
# ERR | Starting, scanning software directory...
Traceback (most recent call last):
  File "C:\Users\Назар\Downloads\minecraft-plugin-downloader-b2.1\minecraft-plugin-downloader-b2.1\manager.py", line 242, in <module>
    main()
  File "C:\Users\Назар\Downloads\minecraft-plugin-downloader-b2.1\minecraft-plugin-downloader-b2.1\manager.py", line 31, in main
    with os.scandir(load("data/config.json", default=CONFIG).json["sources_folder"]) as directory:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'software'

Can i fix this?

**Comment by nazarhktwitch** [comment]
Oh, i just opened not right file
